In [1]:
import tensorflow as tf

**Initialization of Tensors**

```
Create a tensor
```

In [3]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


```
Specify shape and dtype of tensor
```

In [5]:
a = tf.constant(4, shape = (1,1) , dtype = tf.float32)
print(a)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [7]:
a1 = tf.constant([[1,2,3] , [4,5,6]])
print(a1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
a2 = tf.ones((3,3))
print(a2)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [9]:
a3 = tf.zeros((2,3))
print(a3)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [11]:
# identity martix
a4 = tf.eye(3)
print(a4)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


```
Normal Distribution Matrix
```

In [12]:
a5 = tf.random.normal((3,3), mean=0, stddev=1)
print(a5)

tf.Tensor(
[[ 0.96134263  0.4879774   0.29639354]
 [ 0.40836278  0.18420948  0.84920794]
 [-0.59662205 -1.1685917  -1.8175701 ]], shape=(3, 3), dtype=float32)


In [13]:
a6 = tf.range(start=1, limit=10, delta=2)
print(a6)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


**Mathematical Operations**

In [16]:
b = tf.constant([1,2,3])
b1 = tf.constant([9,8,7])
sum = tf.add(b , b1)
sub = tf.subtract(b, b1)
div = tf.divide(b, b1)
mul = tf.multiply(b, b1)
print(sum)
print(sub)
print(div)
print(mul)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [17]:
# dot product
dotp = tf.tensordot(b, b1, axes=1)
print(dotp)

tf.Tensor(46, shape=(), dtype=int32)


In [18]:
exp = b ** 5
print(exp)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [24]:
# matrix multiplication
b2 = tf.random.normal((2,3))
b3 = tf.random.normal((3,4))
matmul = tf.matmul(b2, b3)
print(matmul)
print(b2 @ b3)

tf.Tensor(
[[ 0.08016206 -0.5158484   2.546534    1.2433774 ]
 [-0.4798804  -2.897427   -0.20089734 -0.84337354]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.08016206 -0.5158484   2.546534    1.2433774 ]
 [-0.4798804  -2.897427   -0.20089734 -0.84337354]], shape=(2, 4), dtype=float32)


**Indexing**

In [27]:
b4 = tf.constant([0,1,2,3,4,5,6,7,8])
print(b4[:])
print(b4[1:])
print(b4[1:3])
print(b4[::2])

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [29]:
# get index wise value
x_ind = tf.gather(b4 , [0,3])
print(x_ind)

tf.Tensor([0 3], shape=(2,), dtype=int32)


In [30]:
# reshaping
b5 = tf.range(9)
print(b5)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [31]:
b6 = tf.reshape(b5 , (3,3))
print(b6)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [34]:
#trnapose
b7 = tf.transpose(b6 , perm = [ 1,0])
print(b7)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
